// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xogkeiltcaxiikmsxsih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZ2tlaWx0Y2F4aWlrbXN4c2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzYwMjAsImV4cCI6MjA1ODE1MjAyMH0.PLfCict-b5rDDnCyndR2jQFIvQp8YmiKSpaKxfb3RDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);